name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v3

      - name: Build
        run: just build

      - name: Test
        run: just test

      - name: Check by Rustfmt
        run: just fmt-check

      - name: Check by Clippy
        run: just clippy-check
